export const mealsData = [
    {name: "Chicken noodle soup", season: "Winter", eaten: 5},
    {name: "Pizza", season: "All", eaten: 14},
    {name: "Sushi", season: "All", eaten: 9},
    {name: "Lasagna", season: "All", eaten: 7},
    {name: "Toasted cheese", season: "All", eaten: 34},
    {name: "Bacon and eggs", season: "All", eaten: 6},
    {name: "Fish and chips", season: "Summer", eaten: 11},
    {name: "Butternut soup", season: "Winter", eaten: 18},
    {name: "teriyaki chicken & veggies", season: "Spring", eaten: 6},
    {name: "Snitzels burgers", season: "Summer", eaten: 10},
    {name: "Pie & salad", season: "all", eaten: 5},
    {name: "Pork Bangers & Spuds", season: "Winter", eaten: 11},
    {name: "Pancakes", season: "All", eaten: 4},
    {name: "Easy Cheesy bread lasagna", season: "Autumn", eaten: 7},
    {name: "Barley risotto", season: "Autumn", eaten: 9},
    {name: "Hot dogs", season: "All", eaten: 14},
    {name: "Chicken strips w/ sweet potato fries ", season: "All", eaten: 12},
];